### ISSUE TITLE
build with mbedtls v2.16.0 fails

### ISSUE THREAD

**Issue by SvenRoederer** [bmx-routing/bmx7#41]
OpenWrt went up mbedtls v2.16.0 in https://github.com/openwrt/openwrt/commit/e8f230251654edc43432c20f49ee33b67cabf6c9 which breaks building bmx7. The problems is caused by 

> bmx7-r2018042501/crypt.c:191: undefined reference to `MBEDTLS_DEPRECATED_STRING_CONSTANT'

the relevant log you can see in :
* https://github.com/freifunk-berlin/firmware/commit/0a3fa9a6c56600b1a3e19b1a5cc59c7cc1b32c76
* https://buildbot.berlin.freifunk.net/builders/ar71xx-mikrotik/builds/1078/steps/shell/logs/stdio (search for MBEDTLS_DEPRECATED)

**Comment by axn** [comment]
So the solution is to define -DCRYPTLIB=MBEDTLS_2_8_0 when compiling bmx7 with a mbedTls version greater 2.8.0 (such as 2.16.0) as commented in https://github.com/openwrt-routing/packages/pull/450
Assuming that issue can be closed, please reopen otherwise

**Comment by db4rne** [comment]
This is fixed now for OpenWRT, but no other distro with a recent version of mbedTLS. With Arch Linux for example, I hit the same bug. If the fix doesn't break old distros, maybe we could just make the flag the default?

**Comment by axn** [comment]
Ok, I'll take care of making  -DCRYPTLIB=MBEDTLS_2_8_0 the default in bmx7 master branch. If a distro doesn't have this version it could still define a lower one when upgrading its BMx7 package next time

Am 26. Februar 2019 22:10:09 MEZ schrieb Arne <notifications@github.com>:
>This is fixed now for OpenWRT, but no other distro with a recent
>version of mbedTLS. With Arch Linux for example, I hit the same bug. If
>the fix doesn't break old distros, maybe we could just make the flag
>the default?
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/bmx-routing/bmx7/issues/41#issuecomment-467614813

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by axn** [comment]
Applied default CRYPTLIB=MBEDTLS_2_8_0  in master branch via https://github.com/bmx-routing/bmx7/commit/3db1586dc5818a326e01672595329d2c13a5b13a
